### ISSUE TITLE
About Big sur

### ISSUE THREAD

**Issue by zhangmx1995** [ahadrox/ASRock-B460M-Pro4-OpenCore-Hackintosh#1]
excuse me , but will it work on big sur ?

**Comment by ahaadkabir** [comment]
Hello @zhangmx1995 
If you want to install macOS big sur than ensure that you have the latest version of OpenCore, kexts and config.plist so it won't have any odd compatibility issues. And as the macOS big sur is in beta testing platform I never test it by myself. But I might be testing it out when the 1st stable release gets out. Thank you.

**Comment by ahaadkabir** [comment]
Also, if you want to test it right away, you might go through [this](https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#installation)

**Comment by zhangmx1995** [comment]
OK,Thanks a lot

**Comment by ahaadkabir** [comment]
You're welcome.
